# Github Page へデプロイする
name: GitHub Pages Deploy

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest  
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: npm install
              working-directory: ./webapp
            - name: Build
              run: npm run build
              working-directory: ./webapp
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./webapp/dist